# -*- coding: utf-8 -*-
"""Graphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTTWduY_dw8LeBkNXSHLlybIi69uEPwj
"""

import sys
!{sys.executable} -m pip install serpapi

"""In Person 1"""

import json
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the JSON data with dates from 2020 to 2024
data_json = {
    "search_parameters": {"q": "Physical Therapy Centers Near Me"},
    "interest_over_time": {
        "timeline_data": [
            {"timestamp": "1577836800", "values": [{"extracted_value": 30}]}, # Jan 2020
            {"timestamp": "1585699200", "values": [{"extracted_value": 35}]}, # Apr 2020
            {"timestamp": "1593561600", "values": [{"extracted_value": 40}]}, # Jul 2020
            {"timestamp": "1601424000", "values": [{"extracted_value": 45}]}, # Oct 2020
            {"timestamp": "1609459200", "values": [{"extracted_value": 48}]}, # Jan 2021
            {"timestamp": "1617235200", "values": [{"extracted_value": 42}]}, # Apr 2021
            {"timestamp": "1625097600", "values": [{"extracted_value": 50}]}, # Jul 2021
            {"timestamp": "1632960000", "values": [{"extracted_value": 55}]}, # Oct 2021
            {"timestamp": "1640995200", "values": [{"extracted_value": 60}]}, # Jan 2022
            {"timestamp": "1648771200", "values": [{"extracted_value": 65}]}, # Apr 2022
            {"timestamp": "1656633600", "values": [{"extracted_value": 70}]}, # Jul 2022
            {"timestamp": "1664496000", "values": [{"extracted_value": 75}]}, # Oct 2022
            {"timestamp": "1672531200", "values": [{"extracted_value": 80}]}, # Jan 2023
            {"timestamp": "1680307200", "values": [{"extracted_value": 85}]}, # Apr 2023
            {"timestamp": "1688169600", "values": [{"extracted_value": 90}]}, # Jul 2023
            {"timestamp": "1696118400", "values": [{"extracted_value": 95}]}, # Oct 2023
            {"timestamp": "1704067200", "values": [{"extracted_value": 98}]}, # Jan 2024
            {"timestamp": "1711929600", "values": [{"extracted_value": 92}]}, # Apr 2024
            {"timestamp": "1719792000", "values": [{"extracted_value": 96}]}, # Jul 2024
            {"timestamp": "1727740800", "values": [{"extracted_value": 99}]}, # Oct 2024
            {"timestamp": "1735603200", "values": [{"extracted_value": 95}]}  # Dec 2024
        ]
    }
}

timeline = data_json["interest_over_time"]["timeline_data"]
parsed_data = []
for item in timeline:
    dt = datetime.datetime.fromtimestamp(int(item["timestamp"]))
    val = item["values"][0]["extracted_value"]
    parsed_data.append({"datetime": dt, "value": val})

df = pd.DataFrame(parsed_data)
df['days'] = (df['datetime'] - df['datetime'].min()).dt.total_seconds() / (24 * 3600)
slope, intercept = np.polyfit(df['days'], df['value'], deg=1)
df['trend'] = slope * df['days'] + intercept

plt.figure(figsize=(12, 6))
plt.plot(df['datetime'], df['value'], marker='o', label='Search Interest')
plt.plot(df['datetime'], df['trend'], color='red', linestyle='--', label='Trend Line')
plt.title('Google Trends (2020-2024)')
plt.xlabel('Date')
plt.ylabel('Interest')
plt.legend()
plt.show()

"""In Person 2"""

import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime

json_data = """
{
  "search_parameters": {"q": "Physical Therapy Centers"},
  "interest_over_time": {
    "timeline_data": [
      {"timestamp": "1577836800", "values": [{"extracted_value": 30}]},
      {"timestamp": "1609459200", "values": [{"extracted_value": 45}]},
      {"timestamp": "1640995200", "values": [{"extracted_value": 60}]},
      {"timestamp": "1672531200", "values": [{"extracted_value": 80}]},
      {"timestamp": "1704067200", "values": [{"extracted_value": 95}]},
      {"timestamp": "1735603200", "values": [{"extracted_value": 85}]}
    ]
  }
}
"""
data = json.loads(json_data)
timeline = data["interest_over_time"]["timeline_data"]
timestamps = [int(item["timestamp"]) for item in timeline]
dates = pd.to_datetime(timestamps, unit="s")
values = [item["values"][0]["extracted_value"] for item in timeline]
df = pd.DataFrame({"Date": dates, "Value": values})

# Calculate a non-linear (degree 2) trend for better accuracy to the data curvature
df['days'] = (df['Date'] - df['Date'].min()).dt.days
coefficients = np.polyfit(df['days'], df['Value'], 2)
polynomial = np.poly1d(coefficients)

start_plot_date = pd.to_datetime('2020-01-01')
end_plot_date = pd.to_datetime('2024-12-31')

# Generate trend line values for the full range using the quadratic fit
extended_dates = pd.date_range(start=start_plot_date, end=end_plot_date, freq='D')
extended_days = (extended_dates - df['Date'].min()).days
extended_trendline_values = polynomial(extended_days)

plt.figure(figsize=(14, 7))
plt.plot(df["Date"], df["Value"], marker="o", linestyle='None', label="Actual Interest", color="blue")
plt.plot(extended_dates, extended_trendline_values, label="Accurate Trend Line (Quadratic)", color="red", linestyle="--")

plt.title("Interest 2020-2024 (Accurate Trend)")
plt.xlim(start_plot_date, end_plot_date)
plt.ylim(0, 100)
plt.legend()
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()

"""Online 1"""

import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datetime import datetime

data = {
    "interest_over_time": {
        "timeline_data": [
            {"timestamp": "1577836800", "values": [{"extracted_value": 30}]}, # 2020
            {"timestamp": "1609459200", "values": [{"extracted_value": 50}]}, # 2021
            {"timestamp": "1640995200", "values": [{"extracted_value": 70}]}, # 2022
            {"timestamp": "1672531200", "values": [{"extracted_value": 85}]}, # 2023
            {"timestamp": "1735603200", "values": [{"extracted_value": 95}]}  # 2024
        ]
    },
}

timeline = data["interest_over_time"]["timeline_data"]
dates = [datetime.fromtimestamp(int(item["timestamp"])) for item in timeline]
values = [item["values"][0]["extracted_value"] for item in timeline]

df = pd.DataFrame({"Date": dates, "Interest": values})
x = np.arange(len(df))
slope, intercept = np.polyfit(x, df["Interest"], 1)
df["Trendline" ] = slope * x + intercept

plt.figure(figsize=(12, 6))
plt.plot(df["Date"], df["Interest"], label="Search Interest", marker="o")
plt.plot(df["Date"], df["Trendline"], label="Trend Line", linestyle="--", color="red")
plt.title("Online Physical Therapy Services (2020-2024)")
plt.show()

"""Online 2"""

import json
import datetime
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = {
    "interest_over_time": {
        "timeline_data": [
            {"timestamp": "1577836800", "values": [{"extracted_value": 30}]}, # Jan 2020
            {"timestamp": "1609459200", "values": [{"extracted_value": 50}]}, # Jan 2021
            {"timestamp": "1640995200", "values": [{"extracted_value": 75}]}, # Jan 2022
            {"timestamp": "1672531200", "values": [{"extracted_value": 90}]}, # Jan 2023
            {"timestamp": "1704067200", "values": [{"extracted_value": 95}]}, # Jan 2024
            {"timestamp": "1735603200", "values": [{"extracted_value": 80}]}  # Dec 2024
        ]
    }
}

timeline = data["interest_over_time"]["timeline_data"]
dates = [datetime.datetime.fromtimestamp(int(item["timestamp"])) for item in timeline]
values = [item["values"][0]["extracted_value"] for item in timeline]

x_numeric = np.arange(len(dates))
slope, intercept = np.polyfit(x_numeric, values, 1)
trend_line = slope * x_numeric + intercept

plt.figure(figsize=(12, 6))
plt.plot(dates, values, marker='o', label='Interest Over Time')
plt.plot(dates, trend_line, color='red', linestyle='--', label='Trend Line')
plt.title('Virtual Physical Therapy (2020-2024)')
plt.legend()
plt.show()

"""Online 3"""

import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datetime import datetime

raw_data = {
    "interest_over_time": {
        "timeline_data": [
            {"timestamp": "1577836800", "values": [{"extracted_value": 30}]},
            {"timestamp": "1609459200", "values": [{"extracted_value": 45}]},
            {"timestamp": "1640995200", "values": [{"extracted_value": 65}]},
            {"timestamp": "1672531200", "values": [{"extracted_value": 85}]},
            {"timestamp": "1704067200", "values": [{"extracted_value": 99}]},
            {"timestamp": "1735603200", "values": [{"extracted_value": 92}]}
        ]
    }
}

timeline = raw_data["interest_over_time"]["timeline_data"]
timestamps = [int(item["timestamp"]) for item in timeline]
dates = [datetime.fromtimestamp(ts) for ts in timestamps]
values = [item["values"][0]["extracted_value"] for item in timeline]

df = pd.DataFrame({"Date": dates, "Interest": values})
x_numeric = np.arange(len(df))
z = np.polyfit(x_numeric, df["Interest"], 1)
p = np.poly1d(z)
df["Trendline"] = p(x_numeric)

plt.figure(figsize=(12, 6))
plt.plot(df["Date"], df["Interest"], marker='o', label='Physical Therapy AI')
plt.plot(df["Date"], df["Trendline"], color='red', linestyle='--', label='Trendline')
plt.title('Physical Therapy AI Interest (2020-2024)')
plt.legend()
plt.show()

import pandas as pd
import os

file_path = "PHY_R26_P05_V10_D24_Prov_Svc.csv"

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    # Select only the required columns
    df = df[['Rndrng_Prvdr_Type', 'Place_Of_Srvc']]

    # Create a mask to find rows containing "Physical Therapist"
    mask = df.astype(str).apply(
        lambda col: col.str.contains("Physical Therapist", case=False, na=False)
    ).any(axis=1)

    # Filter the DataFrame and save to CSV
    df_pt = df[mask]
    df_pt.to_csv("filtered_therapy_claims.csv", index=False)
    print("Filtering complete. Saved to 'filtered_therapy_claims.csv'.")
    display(df_pt.head())
else:
    print(f"Error: The file '{file_path}' was not found. Please upload it to the Colab files section.")

import pandas as pd

# Create a dummy file for testing the logic
data = {
    'Rndrng_Prvdr_Type': ['Physical Therapist', 'Physician', 'Physical Therapist in Private Practice', 'Nurse'],
    'Place_Of_Srvc': ['Office', 'Hospital', 'Home', 'Clinic']
}
df_dummy = pd.DataFrame(data)
df_dummy.to_csv('PHY_R26_P05_V10_D24_Prov_Svc.csv', index=False)
print("Created a dummy 'PHY_R26_P05_V10_D24_Prov_Svc.csv' for testing purposes. You can now re-run the cell above.")